demo6/booktest/urls.py
from django.conf.urls import url

from . import views

app_name = 'booktest'

urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^login/$',views.login,name='login'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^register/$',views.register,name='register'),
    url(r'^user_register/$',views.user_register,name='user_register'),
    url(r'^reader/(\d+)/$',views.reader,name='reader'),
    url(r'^reader_query/(\d+)/$',views.reader_query,name='reader_query'),
    url(r'^reader_info/(\d+)/$',views.reader_info,name='reader_info'),
    url(r'^reader_modify/(\d+)/$',views.reader_modify,name='reader_modify'),
    url(r'^reader_updatemodify/$',views.reader_updatemodify,name='reader_updatemodify'),
    url(r'^reader_book/(\d+)/(\d+)/$',views.reader_book,name='reader_book'),
    url(r'^reader_histroy/(\d+)/$',views.reader_histroy,name='reader_histroy'),
    url(r'^manager/(\d+)/$',views.manager,name='manager'),
    url(r'^manager_login/$',views.manager_login,name='manager_login'),
    url(r'^upload/$',views.upload,name='upload'),
    url(r'^edit/$',views.edit,name='edit'),
    url(r'^mail/$',views.mail,name='mail'),
    url(r'^active/(.*?)/$',views.active,name='active'),
    url(r'^ajax/$',views.ajax,name='ajax'),
    url(r'^ajaxa/$',views.ajaxa,name='ajaxa'),
    url(r'^ajaxlogin/$',views.ajaxlogin,name='ajaxlogin'),
    url(r'^checkuser/$',views.checkuser,name='checkuser'),
    url(r'^verifycode/$',views.verifycode,name='verifycode'),
]

demo6/demo6/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('booktest/', include('booktest.urls',namespace='booktest') ),
]

demo6/booktest/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField

# Create your models here.

class Users(User):
    college = models.CharField(max_length=20)
    num = models.CharField(max_length=20)


class Books(models.Model):
    book_name = models.CharField(max_length=20,null=False)
    author = models.CharField(max_length=20,null=False)
    publish_com = models.CharField(max_length=20,null=False)
    publish_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.book_name

class Histroys(models.Model):
    book_id = models.ForeignKey('Books',on_delete=models.CASCADE)
    user_id = models.ForeignKey('Users',on_delete=models.CASCADE)
    user_name = models.CharField(max_length=20,null=False)
    date_borrow = models.DateTimeField(auto_now_add=True)
    date_return = models.DateTimeField()
    status = models.CharField(max_length=20,default='not return')

class Hostpic(models.Model):
    name = models.CharField(max_length=20)
    pic = models.ImageField(upload_to='hostpic')
    index = models.SmallIntegerField()
    def __str__(self):
        return self.name

class MessageInfo(models.Model):
    mname = models.CharField(max_length=20)
    hcontent = HTMLField()
    def __str__(self):
        return self.mname

demo6/booktest/forms.py
from django.forms import ModelForm
from .models import Users,Books
class UsersForm(ModelForm):
    class Meta():
        model = Users
        fields = ['username','password','email','college','num']

# class BooksForm(ModelForm):
#     class Meta():
#         model = Books
#         fields = ['ISBN','book_name','author','publish_com','publish_date']

demo6/booktest/views.py
from django.shortcuts import render,redirect,reverse
from .forms import UsersForm
from .models import *
from django.http import HttpResponse
import datetime
import time
from django.contrib.auth.hashers import check_password,make_password
from django.core.mail import send_mail,send_mass_mail
from django.conf import settings
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer,BadSignature,SignatureExpired
import io,random
from PIL import Image,ImageDraw,ImageFont
from django.views.decorators.cache import cache_page
from django.core.cache import cache

# Create your views here.

# @cache_page(60*15)
def index(request):
    messageinfos = MessageInfo.objects.all()
    hostpics = Hostpic.objects.all().order_by('index')

    result = cache.get("core")
    print(result)
    result = cache.set("core",123)
    print(result)
    result = cache.get("core")
    print(result)

    return render(request,'booktest/index.html',{"hostpics":hostpics,"messageinfos":messageinfos})

def login(request):
    return render(request,'booktest/reader_login.html',{"form":UsersForm()})

def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        result = Users.objects.all().filter(username = username).filter(password = password)
        if len(result)>0:
            return redirect(reverse('booktest:reader',args=(result[0].id,)))
        return HttpResponse(result)
    else:
        return HttpResponse("登录失败")

def register(request):
    return render(request,'booktest/register.html',{"form":UsersForm()})

def user_register(request):
    if request.method == "POST":
        user = UsersForm(request.POST)
        username = request.POST['username']
        passsword = request.POST['password']
        password1 = request.POST['password1']
        email = request.POST['email']
        if passsword == password1:
            if user.is_valid():
                user = user.save(commit=False)
                user.is_active = False
                user.save()
                id = Users.objects.get(username=username).id
                # 1得到序列化工具
                serutil = Serializer(settings.SECRET_KEY, 60)
                result =  serutil.dumps({"userid":id}).decode("utf-8")
                send_mail("点击激活账户", "<a href='http://127.0.0.1:8000/booktest/active/%s'>点击链接激活账户</a>"%(result,),
                          settings.DEFAULT_FROM_EMAIL, [email])
                return redirect(reverse('booktest:login'))
            else:
                return HttpResponse("注册失败")
        else:
            return HttpResponse('密码不一致')
    else:
        return HttpResponse("注册失败")

def reader_query(request,id):
    user = Users.objects.get(pk=id)
    books = None
    if request.method == "POST":
        if request.POST['item'] == 'name':
            name = request.POST['query']
            books = Books.objects.all().filter(book_name= name)
        else:
            author = request.POST['query']
            books = Books.objects.all().filter(author= author)
    return render(request,'booktest/reader_query.html',{"user":user,"books":books})

def reader_info(request,id):
    user = Users.objects.get(pk=id)
    return render(request,'booktest/reader_info.html',{"user":user})

def reader_modify(request,id):
    user = Users.objects.get(pk=id)
    return render(request,'booktest/reader_modify.html',{"user":user})

def reader_updatemodify(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        college = request.POST['college']
        number = request.POST['number']
        email = request.POST['email']
        print("============================================",username)
        id = request.POST['id']
        user = Users.objects.get(pk=id)
        user.username = username
        if password:
            user.password = password
        user.college = college
        user.num = number
        user.email = email
        user.save()
        return redirect(reverse('booktest:reader_info',args=(id,)))

def reader_book(request,uid,bid):
    book = Books.objects.get(pk=bid)
    user = Users.objects.get(pk=uid)
    error =None
    if request.method == "GET":
        reader = Histroys.objects.all().filter(book_id=book)
        return render(request, 'booktest/reader_book.html', {"user": user, "book": book, "reader": reader})
    elif request.method == "POST":
        rea = Histroys.objects.all().filter(book_id=book)
        if rea:
            error = '已经被借阅了'
            return redirect(reverse('booktest:reader_book', args=(uid, bid,)))
        else:
            reader = Histroys()
            reader.book_id = book
            reader.user_id = user
            reader.user_name = user.username
            reader.date_return = time.strftime('%Y-%m-%d',time.localtime(time.time() + 2600000))
            reader.save()
            return redirect(reverse('booktest:reader_book',args=(uid,bid,)))
        # return render(request, 'booktest/reader_book.html', {"user": user, "book": book, "reader": reader})

def reader_histroy(request,uid):
    user = Users.objects.get(pk=uid)
    history = Histroys.objects.all().filter(user_id=user,status='return' )
    return render(request, 'booktest/reader_histroy.html', { "histroys": history,"user":user})

def reader(request,id):
    user = Users.objects.get(pk=id)
    return render(request,'booktest/reader.html',{"user":user})


def manager(request,id):
    admin = User.objects.get(pk=id)
    return render(request,'booktest/manager.html',{'admin':admin})

def manager_login(requset):
    if requset.method == 'GET':
        return render(requset,'booktest/manager_login.html')
    elif requset.method == 'POST':
        username = requset.POST['username']
        password = requset.POST['password']
        admin = User.objects.get(username=username)
        if check_password(password,admin.password):
            return redirect(reverse('booktest:manager',args=(admin.id,)))
        else:
            print(admin)
            error = '用户名或者密码不对'
            return render(requset,'booktest/manager_login.html',{'error':error})

def upload(request):
    if request.method == "GET":
        return render(request,'booktest/reader_upload.html')
    elif request.method == "POST":
        name = request.POST['name']
        index = request.POST['index']
        # 文件数据需要使用FILES 获取 enctype="multipart/form-data"
        pic = request.FILES['pic']
        hp = Hostpic(name=name,index=index,pic=pic)
        hp.save()
        return redirect(reverse('booktest:index'))

def edit(request):
    if request.method == "GET":
        return render(request,'booktest/edit.html')
    elif request.method == "POST":
        mname = request.POST["mname"]
        hcontent = request.POST["hcontent"]
        msg = MessageInfo(mname=mname,hcontent=hcontent)
        msg.save()
        return redirect(reverse('booktest:index'))

def mail(request):
    '''发送邮件'''
    try:
        send_mail("Django发送邮件", "<a href='http://127.0.0.1:8000/booktest/'>点击链接</a>",
                  settings.DEFAULT_FROM_EMAIL, ["1768804958@qq.com",])
    except Exception as e:
        return HttpResponse("发送失败")
    return HttpResponse("发送成功")

def active(request,idstr):
    # 1得到序列化工具
    serutil = Serializer(settings.SECRET_KEY,60)
    try:
        obj = serutil.loads(idstr)
        user = Users.objects.get(pk=obj["userid"])
        user.is_active = True
        user.save()
        return redirect(reverse('booktest:login'))
    except SignatureExpired :
        return HttpResponse("验证码失效了")

def ajax(request):
    return render(request,'booktest/ajax.html')

def ajaxa(request):
    if request.method == "GET":
        return HttpResponse("GET请求成功")
    elif request.method == "POST":
        return HttpResponse("POST请求成功")

def ajaxlogin(request):
    if request.method == "GET":
        return render(request,'booktest/ajaxlogin.html')
    elif request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        verifycode = request.POST['verifycode']
        user = Users.objects.filter(username=username,password=password).first()
        if user is None:
            return HttpResponse('登录失败')
        else:
            if verifycode == request.session.get("verifycode"):
                return HttpResponse("登录成功")
            else:
                return HttpResponse("验证码错误")

def checkuser(request):
    if request.method == "POST":
        username = request.POST["username"]
        user = Users.objects.filter(username= username).first()
        if user is None:
            return HttpResponse("不存在该用户")
        else:
            return HttpResponse("存在该用户")

def verifycode(request):
    # 定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100),
               random.randrange(20, 100),
               random.randrange(20, 100))
    width = 100
    heigth = 25
    # 创建画面对象
    im = Image.new('RGB', (width, heigth), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点
    for i in range(0,100):
        xy = (random.randrange(0,width),random.randrange(0, heigth))
        fill = (random.randrange(0,255),255,random.randrange(0, 255))
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    print(rand_str,'++++++++++')
    # 构造字体对象
    font = ImageFont.truetype('STXINGKA.TTF', 23)
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
    # 释放画笔
    del draw

    # 将生产的验证码存入session

demo6/templates/booktest/ajax.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ajax</title>
    <script src="/static/js/jquery-2.1.4.js" type="text/javascript" charset="utf-8"></script>
    <script>
        $(function () {
            $("#load").click(function () {
                console.log('标签加载完毕');
                $.ajax({
                    url:'/booktest/ajaxa/',
                    type:'post',
                    data:{"csrfmiddlewaretoken": $("input[name=csrfmiddlewaretoken]").val()},
                    success:function (data) {
                        console.log(data);
                    }
                })
            })
        })

    </script>
</head>
<body>
    {% csrf_token %}
    <button id="load">点击load内容</button>
    <div id="info"></div>
    <div id="info2"></div>
</body>
</html>

demo6/templates/booktest/index.html
{% extends "booktest/layout.html" %}
{% block title %}主页{% endblock %}
{% block link %}
  <a href="{% url 'booktest:manager_login' %}">管理员登录 </a>|
  <a href="{% url 'booktest:login' %}">读者登录 </a>
{% endblock %}

{% load cache %}
{% block body %}
  <h2>欢迎使用</h2>
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    {% cache 500 info %}
  <!-- Indicators -->
  <ol class="carousel-indicators">
    {% for pic in hostpics %}
    {% if pic.index == 0%}
    <li data-target="#carousel-example-generic" data-slide-to="{{pic.index}}" class="active"></li>
    {% else %}
    <li data-target="#carousel-example-generic" data-slide-to="{{pic.index}}"></li>
    {% endif %}
    {% endfor %}
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    {% for pic in hostpics %}
    {% if pic.index == 0%}
    <div class="item active">
      <img src="/static/media/{{pic.pic.url}}" alt="加载失败">
      <div class="carousel-caption">
      </div>
    </div>
    {% else %}
    <div class="item ">
      <img src="/static/media/{{pic.pic.url}}" alt="加载失败">
      <div class="carousel-caption">
      </div>
    </div>
    {% endif %}
    {% empty %}
      <h1>没有图片</h1>
    {% endfor %}
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
    {% endcache %}
  </div>
  <div class="articles">
    {% for message in messageinfos %}
      {{message.hcontent|safe}}
    <hr>
    {% endfor %}
  </div>
{% endblock %}

demo6/templates/booktest/layout.html
<!doctype html>
<title> {% block title %} 图书管理系统 {% endblock %} </title>
<link rel=stylesheet type=text/css href="/static/css/style.css">
<script src="/static/js/jquery-2.1.4.js" type="text/javascript" charset="utf-8"></script>
<link rel=stylesheet type=text/css href="/static/css/bootstrap.css">
<script src="/static/js/bootstrap.js" type="text/javascript" charset="utf-8"></script>
{% block linkcss %}

{% endblock %}
<div class=page>
  <h1>图书管理系统</h1>
  <div class=navigation>
    {% block link %}{% endblock %}
  </div>
  <div class=body>
    {% block body %}{% endblock %}
   </div>
  <div class=footer>
     &mdash; 华中科技大学
  </div>
</div>
    

demo6/templates/booktest/manager.html
{% extends 'booktest/layout.html' %}
{% block title%} 功能导航 {% endblock %}
{% block link%} 
	<a href="#"> 注销 [{{ admin.username}}]</a> |
	<a href="#"> 图书管理 </a> |
	<a href="#"> 用户管理 </a>
{%  endblock%}

demo6/templates/booktest/manager_books.html
{% extends 'layout.html' %}
{% block title%} 图书管理 {% endblock %}
{% block link%} 
	<a href="{{ url_for('manager')}}"> 返回 </a> | 
	<a href="{{ url_for('manager_books_add') }}"> 添加 </a> |
	<a href="{{ url_for('manager_books_delete') }}"> 删除 </a> 
{%  endblock%}
{% block body%}
	<h2> 图书管理 </h2>
	<table width="600" border="1", align="center">
	  <tr>
	    <th align="center"> ISBN </th>
	    <th align="center"> 书名 </th>
	    <th align="center"> 作者</th>
	    <th align="centet"> 出版商 </th>
	    <th align="center"> 出版时间 </th>	
	    <th align="center"> 查看信息 </th>
	  </tr>
	  {% for book in books%}
	  <tr>
	    <th align="center"> {{book.book_id}}</th>
	    <th align="center"> {{book.book_name}} </th>
	    <th align="center"> {{book.author}}</th>
	    <th align="centet"> {{book.publish_com}} </th>
	    <th align="center"> {{book.publish_date}}</th>
	    <th align="center"> <a href="{{ url_for('manager_book', id=book.book_id)}}"> 点击进入 </a> </th>
	  </tr>
	  {% endfor %}
	</table>
{% endblock%}

demo6/templates/booktest/manager_books_delete.html
{% extends "layout.html" %}
{% block title %} 删除书目 {% endblock %}
{% block link %}
	<a href="{{ url_for('manager_books')}}"> 返回 </a>
{% endblock %}

{% block body %}
	<h2> 删除书目 </h2>
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
	<form action="" method=post>
	  <dl>
	    <dt>请输入书目ISBN:</dt>
	    <dd><input type=text name=id size=30> </dd>	
    <div class=actions><input type=submit value="删除"></div>
  </form>
{% endblock %}

demo6/templates/booktest/manager_login.html
{% extends "booktest/layout.html" %}
{% block title%} 管理员登录 {% endblock%}
{% block link%} 
	<a href="{% url 'booktest:index' %}"> 返回  </a>
{%  endblock %}
{% block body %}
	<h2> 管理员登录 </h2>
	{% if error %}
	<div class=error>
	  <strong>Error : </strong> {{ error }}
	</div>
	{% endif %}
	<form action="{% url 'booktest:manager_login' %}" method="post">
		{% csrf_token %}
	  <dl>
	    <dt>用户名: </dt>
	    <dd><input type=text name=username size=30> </dd>
	    <dt>密码:	</dt>
	    <dd><input type=password name=password size=30> </dd>
	  </dl>
	  <div class=actions>
	    <input type=submit value="登录">
	  </div>
	</form>
{% endblock %}

demo6/templates/booktest/manager_modify.html
{% extends "layout.html" %}
{% block title %} 修改书目信息 {% endblock %}
{% block link %} 
	{% if book %}
	<a href="{{ url_for('manager_book', id=book.book_id)}}"> 返回 </a>
	{% endif %}
{% endblock %}
{% block body %}
	<h2> 修改书目信息 </h2>
	{% if error %}
	<div class = error>
	  <strong>Error : </strong> {{error}}
	</div>
	{% endif %}
	{% if book %}
	<form action="" method=post>
	  <dl>
	    <dt>书名:</dt>
	    <dd><input type=text name=name size=30 value={{book.book_name}}> </dd>
	    <dt>作者:</dt>
	    <dd><input type=text name=author size=30 value={{book.author}}> </dd>
	    <dt>出版社:</dt>
	    <dd><input type=text name=company size=30 value={{book.publish_com}}> </dd>
	    <dt>出版日期:</dt>
	    <dd><input type=text name=date size=30 value={{book.publish_date}}> </dd>
	  </dl>
	  <div class=actions>
	    <input type=submit value="修改">
	  </div>
	</form>
	{% endif %}
{% endblock %} 

demo6/templates/booktest/manager_users.html
{% extends 'layout.html' %}
{% block title%} 用户管理 {% endblock %}
{% block link%} 
	<a href="{{ url_for('manager')}}"> 返回 </a> 
{%  endblock%}
{% block body%}
	<h2> 用户管理 </h2>
	<table width="600" border="1", align="center">
	  <tr>
	    <th align="center"> 用户名 </th>
	    <th align="center"> 用户信息 </th>
	  </tr>
	  {% for user in users%}
	  <tr>
	    <th align="center"> {{user.user_name}}</th>
	    <th align="center"> <a href="{{ url_for('manager_user', id=user.user_id)}}"> 点击进入 </a> </th>
	  </tr>
	  {% endfor %}
	</table>
{% endblock%}

demo6/templates/booktest/reader_book.html
{% extends 'booktest/layout.html' %}

{% block title %} 书目信息 {% endblock %}
{% block link %} 
	{% if book %}
	<a href="{% url 'booktest:reader' user.id %}"> 返回 </a>
	{% endif %}
{% endblock %}

{% block body %}
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}
	<h2> 书目信息 </h2>
	{% if book %}
	<li> ISBN            	{{book.id}} </li>
	<li> 书名        		{{book.book_name}} </li>
	<li> 作者        		{{book.author}} </li>	
	<li> 出版社     	{{book.publish_com}} </li>
	<li> 出版日期   	{{book.publish_date|date:'Y年m月d日'}} </li>
	{% endif %}
	<div >
	  <h2 > 借阅信息 </h2>
	  {% for readers in reader  %}
	  <li> 借阅者姓名 {{readers.user_name}}</li>
	  <li> 借阅日期  {{readers.date_borrow|date:'Y年m月d日'}}</li>
	  <li> 还书日期  {{readers.date_return}}</li>
	  {% empty %}
	  <li> 无 </li>
	  {% endfor %}
	  <form action="{% url 'booktest:reader_book' user.id book.id %}" method=post>
		  {% csrf_token %}
	    <div class=actions>
	      <input type=submit value="借阅">
	    </div>
	  </form>

{% endblock %}

demo6/templates/booktest/reader_histroy.html
{% extends "booktest/layout.html" %}
{% block title %} 阅读记录 {% endblock %}
{% block link %} 
	<a href="{% url 'booktest:reader' user.id %}"> 返回 </a>
{% endblock %}
{% block body %}
	<table width="600" border="1" align="center">
		<tr>
			<th align="center"> 书名 </th>
			<th align="center"> 借书日期 </th>
			<th align="center"> 还书日期 </th>
			<th align="center"> 状态 </th>
		</tr>
		{% for histroy in histroys %}
			<tr>
				<th align="center"> {{histroy.book_id}} </th>
				<th align="center"> {{histroy.date_borrow}}</th>
				<th align="center"> {{histroy.date_return}} </th>
				<th align="center"> {{histroy.status}} </th>
			</tr>
		{% empty %}
			<h3>没有</h3>
		{% endfor %}
	</table>

{% endblock %}

demo6/templates/booktest/reader_info.html
{% extends "booktest/layout.html" %}
{% block title %} 个人主页 {% endblock %}

{% block link %}
	<a href="{% url 'booktest:reader' user.id %}"> 返回  </a>  |
	<a href="{% url 'booktest:reader_modify' user.id %}"> 修改 </a>
{% endblock %}
{% block body  %}
	<h2> 用户信息 </h2>
	{% if user %}
	<li> 用户名 {{user.username}} </li>
	<li> 学院名 {{user.college}} </li>
	<li> 学号 {{user.num}} </li>
	<li> 邮箱 {{user.email}} </li>
	{% endif %}

{% endblock %}

demo6/templates/booktest/reader_modify.html
{% extends "booktest/layout.html" %}
{% block title %} 个人信息修改 {% endblock %}
{% block link %} 
	<a href="{% url 'booktest:reader' user.id %}"> 返回 </a>
{% endblock %}
{% block body %}
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
	<form action="{% url 'booktest:reader_updatemodify'%}" method='post'>
		{% csrf_token %}
	  <dl>
	    <dt>用户名:</dt>
	    <dd><input type=text name='username' size=30 value={{user.username}}> </dd>
	    <dt>请输入新密码(不输入就是不修改):</dt>
	    <dd><input type=password name='password' size=30> </dd>
	    <dt>学院:</dt>
	    <dd><input type=text name='college' size=30 value={{user.college}}> </dd>
	    <dt>学号:</dt>
	    <dd><input type=text name='number' size=30 value={{user.num}}> </dd>
	    <dt>邮箱:</dt>
	    <dd><input type=text name='email' size=30 value={{user.email}}>
		<input type=hidden name='id' size=30 value={{user.id}}>
		</dd>
	  </dl>
	  <div class=actions><input type=submit value="确定"></div>
	</form>

{% endblock %}

demo6/templates/booktest/register.html
{% extends "booktest/layout.html" %}
{% block title %} 注册 {% endblock %}
{% block link %} 
	<a href="{% url 'booktest:login' %}"> 返回 </a>
{% endblock %}
{% block body %}
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
	<form action="{% url 'booktest:user_register' %}" method="post">
		{% csrf_token %}
	  <dl>
	    <dt>用户名:</dt>
	    <dd>
			{# <input type=text name=username size=30 value="{{ request.form.username}}"> #}
			{{form.username}}
		</dd>
	    <dt>密码:</dt>
	    <dd>
			{# <input type="password" name=password size=30> #}
			{{form.password}}
		</dd>
	    <dt>密码<small>(重复)</small>:	</dt>
	    <dd>
			<input type="password" name="password1">
		</dd>
	    <dt>学院:</dt>
	    <dd>
			{# <input type=text name=college size=30> #}
			{{form.college}}
		</dd>
	    <dt>学号:</dt>
	    <dd>
			{# <input type=text name=number size=30>  #}
			{{form.num}}
		</dd>
	    <dt>邮箱:</dt>
	    <dd>
			{# <input type=text name=email size=30> #}
			{{form.email}}
		</dd>
	  </dl>
	  <div class=actions><input type=submit value="注册"></div>
	</form>

{% endblock %}