demo3/demo3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('polls/',include('polls.urls',namespace='polls'))
]

demo3/polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$',views.votelist,name='list'),
    url(r'^optionlist/(\d+)/$',views.optionlist,name='optionlist'),
    url(r'^votedetail/$',views.votedetail,name='votedetail'),
    # url(r'^optdetail/(\d+)/$',views.optdetail,name='optdetail'),
    url(r'^addvote/$',views.addvote,name='addvote'),
    url(r'^voteadd/$',views.voteadd,name='voteadd'),
    url(r'^updatevote/(\d+)/$',views.updatevote,name='updatevote'),
    url(r'^voteupdate/$',views.voteupdate,name='voteupdate'),
    url(r'^votdelete/(\d+)/$',views.votdelete,name='votdelete'),
    url(r'^addoption/(\d+)/$',views.addoption,name='addoption'),
    url(r'^optionadd/$',views.optionadd,name='optionadd'),
    url(r'^updateoption/(\d+)/$',views.updateoption,name='updateoption'),
    url(r'^optionupdate/$',views.optionupdate,name='optionupdate'),
    url(r'^deleteoption/(\d+)/$',views.deleteoption,name='deleteoption'),
    url(r'^optdetail/(\d+)/$',views.optdetail,name='optdetail'),
]

demo3/polls/models.py
from django.db import models

# Create your models here.

class GoodsManage(models.Manager):
    def create_good(self,_name,_age):
        goods = self.model()
        goods.name = _name
        goods.age = _age
        return goods
    def create_goods(self,_name,_age):
        goods = self.create(name=_name,age=_age)
        return goods

class Goods(models.Model):
    name = models.CharField(max_length=20)
    age = models.IntegerField()
    dgmanager = models.Manager()
    dgmanager1 = GoodsManage()

    @classmethod
    def create(cls,_name,_age):
        goods = cls(name=_name,age = _age)
        return goods

    class Meta():
        db_table = 'goods'
        ordering = ['age','-name']





# 一对
class temp(models.Model):
    name = models.CharField(max_length=20)
# 一
class temp2(models.Model):
    fname = models.CharField(max_length=20)
    uid = models.OneToOneField('temp',on_delete=models.CASCADE)
# 多对
class Host(models.Model):
    hostname = models.CharField(max_length=20)
    ip = models.GenericIPAddressField(protocol='ipv4')
    port = models.IntegerField()
# 多
class Application(models.Model):
    name = models.CharField(max_length=20)
    h = models.ManyToManyField('Host')


class vote(models.Model):
    votename = models.CharField(max_length=50)
    def __str__(self):
        return self.votename

class option(models.Model):
    options = models.CharField(max_length=20)
    number = models.IntegerField(default=0)
    voteid = models.ForeignKey('vote',on_delete=models.CASCADE)

    def __str__(self):
        return self.options

demo3/polls/views.py
from django.shortcuts import render
from .models import vote,option
from django.http import HttpResponse,HttpResponseRedirect

# Create your views here.

def votelist (request):
    try:
        result = vote.objects.all()
        return render(request, 'poll/list.html', {'votes': result})
    except Exception as e:
        print(e)

def addvote(request):
    return render(request,'poll/addvote.html')

def voteadd(request):
    votename = request.POST['votename']
    vot = vote()
    vot.votename = votename
    vot.save()

    return HttpResponseRedirect('/polls/')

def updatevote(request,vid):
    result = vote.objects.get(pk=vid)
    return render(request,'poll/updatevote.html',{"vote":result})

def voteupdate(request):
    votename = request.POST['votename']
    vid = request.POST['vid']

    vot = vote.objects.get(pk=vid)
    vot.votename = votename
    vot.save()

    return HttpResponseRedirect('/polls/')

def votdelete(request,vid):
    vote.objects.get(pk=vid).delete()
    return HttpResponseRedirect('/polls/')

def addoption(request,vid):
    vot = vote.objects.get(pk=vid)
    return render(request,'poll/addoption.html',{"vot":vot})


def optionadd(request):
    vid = request.POST['vid']
    options = request.POST['options']
    number = request.POST['number']

    opt = option()
    opt.options = options
    opt.number = number
    result = vote.objects.get(pk=vid)
    opt.voteid = result
    opt.save()


    return HttpResponseRedirect('/polls/optionlist/'+ str(result.id) +'/')

def updateoption(request,oid):
    result = option.objects.get(pk=oid)
    vot = vote.objects.get(votename=result.voteid)
    return render(request,'poll/updateoption.html',{"result":result,"vot":vot})

def optionupdate(request):
    oid = request.POST['oid']
    options = request.POST['optionname']
    number = request.POST['number']

    h1 = option.objects.get(pk=oid)
    h1.options = options
    h1.number =number
    result = vote.objects.get(votename=h1.voteid)
    h1.voteid = result
    h1.save()

    return HttpResponseRedirect('/polls/optionlist/'+ str(result.id) +'/')

def deleteoption(request,oid):
    opt = option.objects.get(pk=oid)
    result = vote.objects.get(votename=opt.voteid)
    option.objects.get(pk=oid).delete()
    return HttpResponseRedirect('/polls/optionlist/'+ str(result.id) +'/')

def optionlist(request,voteid):
    try:
        vot = vote.objects.get(pk=voteid)
        print(vot.votename)
        result = vot.option_set.all()
        return render(request, 'poll/detail.html', {'options': result, 'vot': vot})
    except Exception as e:
        print(e)

def votedetail(request):
    try:
        if 'option' in request.POST:
            optionid = request.POST['option']
            print(optionid)
            num = option.objects.get(pk=optionid)
            number = num.number + 1
            print(number)
            votid = request.POST['votid']
            print(votid)
            num.number = number
            print(num.number)
            num.save()
            return HttpResponseRedirect('/polls/optdetail/'+ str(votid) +'/')
        else:
            votid = request.POST['votid']
            return HttpResponseRedirect('/polls/optionlist/' + str(votid) + '/')
    except Exception as e:
        print(e)

def optdetail(request,votid):
    vot = vote.objects.get(pk=votid)
    print(vot.id)
    return render(request, 'poll/votdetail.html', { 'vot': vot})

demo3/templates/poll/addoption.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加投票问题选项</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="div1">
        <h1>投票信息：{{vot.votename}}</h1>
        <h3>添加投票问题选项</h3>
        <form action="{% url 'polls:optionadd' %}" method="post">
            投票问题：<input type="text" name="options">
            <br>
            投票数量：<input type="number" name="number">
            <br>
            <input type="hidden" value="{{vot.id}}" name="vid">
            <input type="submit" value="提交">
        </form>
        <a href="{% url 'polls:optionlist' vot.id %}">返回投票问题页</a>
    </div>
</body>
</html>

demo3/templates/poll/addvote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加投票问题</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="div1">
        <h1>添加投票问题</h1>
        <form action="{% url 'polls:voteadd' %}" method="post">
            问题名：<input type="text" name="votename">
            <br>
            <input type="submit" value="提交">
        </form>
        <a href="{% url 'polls:list' %}">返回列表页</a>
    </div>
</body>
</html>

demo3/templates/poll/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票选项页面</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
   <div class="div1">
        <h1>投票信息：{{vot.votename}}</h1>
        <h3>投票选项</h3>
        <form action="{% url 'polls:votedetail' %}" method="post">
            <ul>
                {% for option in options %}
                <li>
                    <input type="radio" name="option" value="{{option.id}}"> {{option.options}}
                    <a href="{% url 'polls:deleteoption' option.id %}">删除</a>
                    <a href="{% url 'polls:updateoption' option.id %}">编辑</a>
                </li>
                {% empty%}
                <h3>该投票没有选项</h3>
                {% endfor %}
            </ul>
            <input type="hidden" name="votid" value="{{vot.id}}">
            <input type="submit" value="提交">
        </form>
        <a href="{% url 'polls:addoption' vot.id %}">添加选项</a>
        <a href="{% url 'polls:list' %}">返回列表页</a>
   </div>
</body>
</html>

demo3/templates/poll/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票页面</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="div1">
        <h1>投票信息汇总</h1>
        <ol>
            {% for vote in votes %}
            <li>
                <a href="{% url 'polls:optionlist' vote.id %}">{{vote.votename}}</a>
                <a href="{% url 'polls:votdelete' vote.id %}">删除</a>
                <a href="{% url 'polls:updatevote' vote.id %}">编辑</a>
            </li>
            {% empty %}
            <li> <h3>没有要投票的列表</h3> </li>
            {% endfor %}
        </ol>
        <a href="{% url 'polls:addvote' %}">添加投票问题</a>
    </div>
</body>
</html>

demo3/templates/poll/updateoption.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑问题</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="div1">
        <h1>编辑投票问题页面</h1>
        <form action="{% url 'polls:optionupdate' %}" method="post">
            投票名：<input type="text" name="optionname" value="{{result.options}}">
            <br>
            投票数：<input type="number" name="number" value="{{result.number}}">
            <br>
            <input type="hidden" value="{{result.id}}" name="oid">
            <input type="submit" value="提交">
        </form>
        <a href="{% url 'polls:optionlist' vot.id %}">返回投票问题页</a>
    </div>
</body>
</html>

demo3/templates/poll/updatevote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改投票问题</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="div1">
        <h1>修改投票问题</h1>
        <form action="{% url 'polls:voteupdate' %}" method="post">
            问题名称：<input type="text" name="votename" value="{{vote.votename}}">
            <br>
            <input type="hidden" value="{{vote.id}}" name="vid">
            <input type="submit" value="提交">
        </form>
        <a href="{% url 'polls:list' %}">返回列表页</a>
    </div>
</body>
</html>

demo3/templates/poll/votdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票结果</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="div1">
        <h1>投票信息：{{vot.votename}}</h1>
        <h3>投票选项</h3>
        <ul>
            {% for option in vot.option_set.all %}
            <li> <h4>{{option.options}} 票数：{{option.number}}</h4></li>
            {% empty%}
            <h3>该投票没有选项</h3>
            {% endfor %}
        </ul>
        <a href="{% url 'polls:optionlist' vot.id %}">返回投票问题页</a>
    </div>
</body>
</html>