demo5/blog/urls.py
from django.conf.urls import url
from . import views
from .feed import ArticleFeed

app_name = 'blog'

urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^index_action/(\d+)/$',views.index_action,name='index_action'),
    url(r'^index_tag/(\d+)/$',views.index_tag,name='index_tag'),
    url(r'^index_time/(\d+)/(\d+)/$',views.index_time,name='index_time'),
    url(r'^single_hr/(\d+)/$',views.single_hr,name='single_hr'),
    url(r'^single/(\d+)/$',views.single,name='single'),
    url(r'^rss/$',ArticleFeed(),name='rss'),
]

demo5/comment/urls.py
from django.conf.urls import url
from . import views
app_name = 'comment'

urlpatterns = [
    url(r'^commitcomment/(\d+)/$',views.commitcomment,name='commitcomment')
]

demo5/demo5/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('blog/',include('blog.urls',namespace='blog')),
    url('blog/',include('comment.urls',namespace='comment')),
]

demo5/blog/models.py
from django.db import models

# Create your models here.


class cation(models.Model):
    cname = models.CharField(max_length=30)
    def __str__(self):
        return self.cname


class tag(models.Model):
    tagname = models.CharField(max_length=30)
    def __str__(self):
        return self.tagname


class comment(models.Model):
    username = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    website = models.CharField(max_length=30)
    content = models.CharField(max_length=30)
    contenttime = models.DateTimeField(auto_now_add=True)
    artid = models.ForeignKey('article',models.CASCADE)
    def __str__(self):
        return self.username


class article(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=30)
    time_creation = models.DateTimeField(auto_now_add=True)
    time_modification = models.DateTimeField(auto_now_add=True)
    number = models.IntegerField(default=0)
    text = models.TextField()
    acation = models.ForeignKey('cation',models.CASCADE)
    atag = models.ManyToManyField(to='tag')
    def __str__(self):
        return self.title

demo5/comment/models.py
from django.db import models
from blog.models import article
# Create your models here.

class Comments(models.Model):
    username = models.CharField(max_length=30)
    email = models.EmailField(blank=True,null=True)
    website = models.URLField(blank=True,null=True)
    content = models.TextField()
    contenttime = models.DateTimeField(auto_now_add=True)
    artid = models.ForeignKey(article,models.CASCADE)
    def __str__(self):
        return self.username

demo5/comment/forms.py
from django.forms import ModelForm
from .models import Comments
class CommentForm(ModelForm):
    class Meta():
        model = Comments
        fields = ['username','email','website','content']

demo5/blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from .models import *
import markdown
from comment.forms import CommentForm

from django.db.models import Q

# Create your views here.

def index(request):
    artis = article.objects.all()
    for art in artis:
        art.text = art.text[0:100]
    return render(request,'blog/index.html',{"artis":artis})

def index_action(request,cid):
    artis = cation.objects.get(pk=cid).article_set.all()
    for art in artis:
        art.text = art.text[0:100]
    return render(request,'blog/index.html',{"artis":artis,})

def index_tag(request,tid):
    artis = tag.objects.get(pk=tid).article_set.all()
    for art in artis:
        art.text = art.text[0:100]

    return render(request,'blog/index.html',{"artis":artis,})

def single_hr(request,aid):
    artis = article.objects.get(pk=aid)
    artis.number = artis.number + 1
    artis.save()
    return HttpResponseRedirect("/blog/single/"+str(aid)+"/")

def single(request,aid):
    artis = article.objects.get(pk=aid)
    # artis.text = markdown.markdown(artis.text,extensions=[
    #     'markdown.extensions.extra',
    #     'markdown.extensions.codehilite',
    #     'markdown.extensions.toc'
    # ])
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc'
    ])
    artis.text = md.convert(artis.text)
    artis.toc = md.toc
    return render(request, 'blog/single.html',{"artis": artis,"form":CommentForm()})


def index_time(request,year,month):
    artis = article.objects.all().filter(time_creation__year=year).filter(time_creation__month=month).order_by('-time_creation')
    for art in artis:
        art.text = art.text[0:100]
    return render(request,'blog/index.html',{"artis":artis,})

demo5/comment/views.py
from django.shortcuts import render,redirect,reverse,get_object_or_404
from django.http import HttpResponse
from .forms import CommentForm
from blog.models import article
# Create your views here.

def commitcomment(request,id):
    art = get_object_or_404(article,pk=id)
    if request.method == "POST":
        comment = CommentForm(request.POST)
        if comment.is_valid():
            comment = comment.save(commit=False)
            comment.artid =art
            comment.save()
            return redirect(reverse('blog:single',args=(id,)))
        else:
            return HttpResponse("评论失败")
    else:
        return HttpResponse("评论失败")

demo5/templates/blog/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

demo5/templates/blog/base.html
{% load extend_fun %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block left %}


                {% endblock %}
            </main>
            <aside class="col-md-4">
                {% block toc %}


                {% endblock %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        {% getarticle as text_time %}
                        {% for att in  text_time %}
                        <li>
                            <a href="{% url 'blog:single_hr' att.id %}">{{att.title}}</a>
                        </li>
                        {% empty %}
                            <h1>没有最新文章</h1>
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% getdatelist as datelist %}
                        {% for s in datelist %}
                        <li>
                            <a href="{% url 'blog:index_time' s.year s.month %}">{{s.year}} 年 {{s.month}} 月</a>
                        </li>
                        {% empty %}
                        <h1>没有发表文章月份</h1>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% getcategorys as cations %}
                        {% for cat in cations %}
                        <li>
                            <a href="{% url 'blog:index_action' cat.id %}">{{cat.cname}} <span class="post-count">({{cat.article_set.all|length}})</span></a>
                        </li>
                        {% empty %}
                            <h1>没有分类</h1>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% gettags as tags %}
                        {% for tag in tags %}
                        <li>
                            <a href="{% url 'blog:index_tag' tag.id %}">{{tag.tagname}}</a>
                        </li>
                        {% empty %}
                        <h1>没有标签云</h1>
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'blog:rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="/static/js/script.js"></script>

</body>
</html>

demo5/templates/blog/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

demo5/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block left %}
    {% for arti in artis %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{% url 'blog:single_hr' arti.id %}">{{arti.title}}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="{% url 'blog:index_action' arti.acation.id %}">{{arti.acation.cname}}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="2012-11-09T23:15:57+00:00">{{arti.time_creation|date:'Y年m月d日'}}</time></a></span>
                <span class="post-author"><a href="#">{{arti.author}}</a></span>
                <span class="comments-link"><a href="#">{{arti.comment_set.all|length}} 评论</a></span>
                <span class="views-count"><a href="#">{{arti.number}} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>
                {{arti.text}}...
            </p>
            <div class="read-more cl-effect-14">
                <a href="{% url 'blog:single_hr' arti.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% empty %}
        <h1>你还没有博客发表，快来发表吧</h1>
    {% endfor %}
    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <div class="pagination">
        <ul>
            <li><a href="">1</a></li>
            <li><a href="">...</a></li>
            <li><a href="">4</a></li>
            <li><a href="">5</a></li>
            <li class="current"><a href="">6</a></li>
            <li><a href="">7</a></li>
            <li><a href="">8</a></li>
            <li><a href="">...</a></li>
            <li><a href="">11</a></li>
        </ul>
    </div>
{% endblock %}

demo5/templates/blog/single.html
{% extends 'blog/base.html' %}

{% block left %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{artis.title}}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="{% url 'blog:index_action' artis.acation.id %}">{{artis.acation.cname}}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="2012-11-09T23:15:57+00:00">{{artis.time_creation|date:'Y年m月d日'}}</time></a></span>
                <span class="post-author"><a href="#">{{artis.author}}</a></span>
                <span class="comments-link"><a href="#">{{artis.comment_set.all|length}} 评论</a></span>
                <span class="views-count"><a href="#">{{artis.number}} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
           {{artis.text|safe}}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comment:commitcomment' artis.id %}" method="post" class="comment-form">
            <div class="row">
                <div class="col-md-4">
                    <label for="form.username.id_for_label">名字：</label>
                    {{form.username}}
                </div>
                <div class="col-md-4">
                    <label for="form.email.id_for_label">邮箱：</label>
                    {{form.email}}
                </div>
                <div class="col-md-4">
                    <label for="form.website.id_for_label">网址：</label>
                    {{form.website}}
                </div>
                <div class="col-md-12">
                    <label for="form.content.id_for_label">评论：</label>
                    {{form.content}}
                    <input type="hidden" value="{{artis.id}}" name="aid">
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{artis.comments_set.all|length}}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comm in artis.comments_set.all %}
                <li class="comment-item">
                    <span class="nickname">{{comm.username}}</span>
                    <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{comm.contenttime}}</time>
                    <div class="text">
                       {{comm.content}}
                    </div>
                </li>
                {% empty %}
                <h1>该文章还没有评论，快来抢沙发吧</h1>
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}

{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{artis.toc|safe}}
    </div>
{% endblock %}