demo1/booktest/urls.py
from django.conf.urls import url
from . import views

app_name = 'booktest'

urlpatterns = [
    url(r'^$', views.index,name='index'),
    # url('index/',views.index),
    url(r'^list/',views.list,name='list'),
    # url(r'index/$',views.index),
    # url(r'detail/(\d+)/(\d+)/$',views.detail),
    url(r'^details/(\d+)/$',views.details,name='details'),
    url(r'^delete/(\d+)/$',views.delete,name='delete'),
    # url(r'^bookadd/(\d+)/$',views.bookadd,name='bookadd'),
    url(r'^heroadd/(\d+)/$',views.heroadd,name='heroadd'),
    url(r'^heroinfoadd/$',views.heroinfoadd,name='heroinfoadd'),
    url(r'^bookadd/$',views.bookadd,name='bookadd'),
    url(r'^addbook/$',views.addbook,name='addbook'),
    url(r'^bookupdate/(\d+)/$',views.bookupdate,name='bookupdate'),
    url(r'^updatebook/$',views.updatebook,name='updatebook'),
    url(r'^herodelete/(\d+)/$',views.herodelete,name='herodelete'),
    url(r'^heroupdate/(\d+)/$',views.heroupdate,name='heroupdate'),
    url(r'^addheroinfo/$',views.addheroinfo,name='addheroinfo'),
    url(r'^area/$',views.area,name='area'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
]

demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('booktest/',include('booktest.urls',namespace='booktest'))
    # url(r'^',include('cookiesessiontest.urls',namespace='cookiesessiontest'))
]


'''
去除硬编码
1. 给应用添加app_name
2. 在项目url配置文件中  在include中给应用添加命名空间
3. 
'''

demo1/booktest/models.py
from django.db import models

# Create your models here.

'''
django MVT M
ORM 对象中的O
需要定义实体类


定义模型：继承models.Model
配置数据库：默认sqlite
将应用名添加到应用列表settings.py文件里

python manage.py makemigrations 生成迁移文件
python manage.py migrate 执行迁移

'''

'''
python manage.py shell 进入命令：不需要运行项目就可以操作数据库

导入类 from booktest.models import HeroInfo,BookInfo
查找所有行  表名.objects.all()
根据主键查找 表名.objects.get(pk=1)
添加对象 **.save()
修改对象  **.save()
删除对象 **delete()

如果存在一对多关系： 一方.多方类名小写_set.all() 可以查询一对多关系

一对多:  一方村子主键   多方存在主键和外键（一方中的主键）

类名.objects.create(列名=值)
'''

class AreaInfo(models.Model):
    atitle = models.CharField(max_length=20)
    aParent = models.ForeignKey('self',null=True,blank=True,on_delete=models.CASCADE)
    def __str__(self):
        return self.atitle


class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.btitle

    def title(self):
        return self.btitle
    title.short_description = '书名'

    def pub_date(self):
        return self.bpub_date
    pub_date.short_description = '日期'

class HeroInfo(models.Model):
    hname = models.CharField(max_length=20)
    hgender = models.BooleanField()
    hcontent = models.CharField(max_length=50)
    # 外键 第一个参数为表名  第二个参数代表删除类型
    hbook = models.ForeignKey('BookInfo',on_delete=models.CASCADE)

    def __str__(self):
        return self.hname

    def name(self):
        return self.hname
    name.short_description = '姓名'

    def gender(self):
        return self.hgender
    gender.short_description = '性别'

    def content(self):
        return self.hcontent
    content.short_description = '绝学'

demo1/booktest/views.py
from django.shortcuts import render,get_list_or_404,get_object_or_404
from django.shortcuts import redirect,reverse
from django.http import  HttpResponse,HttpResponseRedirect
from .models import BookInfo,HeroInfo
from datetime import timedelta
from django.template import loader,RequestContext
# Create your views here.

# 定义视图函数
def index(request):
    # print("请求",request)
    # return HttpResponse('首页')
    # indextem = loader.get_template('booktest/index.html')
    # cont = {"username":"pbs"}
    # # 使用变量参数渲染模板
    # result = indextem.render(cont)
    # # 返回模板
    # return HttpResponse(result)

    # t1 =loader.get_template('booktest/index.html')
    # context = {'username':'asdadasdasdas'}
    # return HttpResponse(t1.render(context))

    # response = HttpResponse()
    # print(dir(request.COOKIES))
    # if 'h1' in request.COOKIES.keys():
    #     response.write('<h1>'+ request.COOKIES['h1'] + '</h1>')
    # response.set_cookie('h1','zzy')
    # return response
    # return HttpResponseRedirect(reverse('booktest:index'))
    return render(request,'booktest/index.html',{"username":request.session.get('username')})


def list(request):
    # return HttpResponse('列表页')
    result = BookInfo.objects.all()
    # 查询列表报错,会调用404页面
    # result = get_list_or_404(BookInfo,pk=30)
    return render(request,'booktest/list.html',{"booklist":result})

def bookadd(request):
    return render(request,'booktest/bookadd.html')

def addbook(request):
    btitle = request.POST['bookname']
    b1 = BookInfo()
    b1.btitle = btitle
    b1.save()
    # return HttpResponseRedirect('/booktest/list/')
    return HttpResponseRedirect(reverse('booktest:list'))

def bookupdate(request,bid):
    result = BookInfo.objects.get(pk=bid)
    # 查询BookInfo 的id,报错会调用404
    # result = get_object_or_404(BookInfo,pk=20)

    return render(request,'booktest/bookupdate.html',{"book":result})

def updatebook(request):
    bookid = request.POST['bookid']
    btitle = request.POST['bookname']
    b1 = BookInfo.objects.get(pk=bookid)
    b1.btitle = btitle
    b1.save()
    # return HttpResponseRedirect('/booktest/list/')
    return HttpResponseRedirect(reverse('booktest:list'))

def detail(request,id,age):
    # return HttpResponse('标签页'+'  '+str(id)+'  '+str(age))
    return render(request,'booktest/list.html')

def details(request,id):
    # try:
    #     result = BookInfo.objects.get(pk=int(id)).btitle
    #     return HttpResponse(result)
    # except Exception as e:
    #     print(e)
    result = BookInfo.objects.get(pk=id)
    return render(request,'booktest/detail.html',{"Bookdata":result})

def delete(request,id):
    try:
        BookInfo.objects.get(pk=id).delete()
        result = BookInfo.objects.all()
        # 使用render没有刷新请求url
        # return render(request, 'booktest/list.html', {"booklist": result})
        # 重新向服务器发起请求 刷新url
        # return HttpResponseRedirect('/booktest/list/',{'booklist':result})
        return HttpResponseRedirect(reverse('booktest:list'),{'booklist':result})
    except Exception as e:
        return HttpResponse("删除失败")

def heroadd(request,bookid):
    return render(request,'booktest/heroadd.html',{'bookid':bookid})

def heroinfoadd(request):
    hname = request.POST['heroname']
    hsex = request.POST['sex']
    hcontent = request.POST['herocontent']
    bookid = request.POST['bookid']

    book  = BookInfo.objects.get(pk=bookid)
    h1 = HeroInfo()
    h1.hname = hname
    h1.hcontent = hcontent
    if hsex == 0:
        h1.hgender = False
    else:
        h1.hgender = True
    h1.hbook = book
    h1.save()

    # return render(request, 'booktest/detail.html', {"Bookdata":book})
    # return HttpResponseRedirect('/booktest/details/'+str(bookid)+'/',{"Bookdata":book})
    return HttpResponseRedirect(reverse('booktest:details',args=str(bookid)),{"Bookdata":book})
    # print(hname,hsex,hcontent,bookid)
    # return HttpResponse('添加成功')

def herodelete(request,hid):
    hero = HeroInfo.objects.get(pk=hid)
    bookid = hero.hbook.id
    # print(bookid.id,"---------------------------")
    # return HttpResponse(bookid)
    HeroInfo.objects.get(pk=hid).delete()
    # book = BookInfo.objects.get(btitle=bookid)
    # bookid = book.id
    # return HttpResponse(bookid)
    # return HttpResponseRedirect('/booktest/details/' + str(bookid) + '/')
    return HttpResponseRedirect(reverse('booktest:details',args=str(bookid)))

def heroupdate(request,hid):
    result = HeroInfo.objects.get(pk=hid)

    return render(request,'booktest/heroupdate.html',{"hero":result})

def addheroinfo(request):
    hname = request.POST['heroname']
    hgender = request.POST['sex']
    hcontent = request.POST['herocontent']
    hbook = request.POST['hbook']
    hid = request.POST['heroid']

    h1 = HeroInfo.objects.get(pk=hid)
    h1.hname = hname
    h1.hgender = hgender
    h1.hcontent = hcontent
    book = BookInfo.objects.get(btitle=hbook)
    h1.hbook = book
    h1.save()
    # return HttpResponseRedirect('/booktest/details/' + str(book.id) + '/')
    # return HttpResponseRedirect(reverse('booktest:details', args=book.id),)
    return HttpResponseRedirect(reverse('booktest:details',args=str(book.id)))


def login(request):
    if request.method == "GET":
        return render(request,'booktest/login.html')
    elif request.method == "POST":
        username = request.POST['username']
        request.session["username"] = username
        # request.session.set_expiry(timedelta(days=5))
        return redirect(reverse('booktest:index'))

def logout(request):
    request.session.clear()
    return redirect(reverse('booktest:index'))

from .models import AreaInfo
def area(request):
    area = AreaInfo.objects.get(atitle='郑州')
    return render(request,'booktest/area.html',{'area':area})


'''
视图函数
将函数和路由绑定
'''

'''
创建模板文件夹 templates
配置模板目录 os.path.join(BASEDIR,'templates')
创建项目模板目录，创建模板

加载模板 loader.get_template()
使用变量渲染模板  result = temp.render({})
返回模板 HttpResponse(result)
'''

demo1/templates/booktest/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加图书</title>
</head>
<body>
    <from action="/booktest/bookadd/" method="post">
        图书名: <input type="text" name="username" id="idname">
        <input type="submit" value="提交">
    </from>
</body>
</html>

demo1/templates/booktest/area.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>地区</title>
</head>
<body>
    当前地区：{{area.atitle}}
    <hr/>
    上级地区：{{area.aParent.atitle}}
    <hr>
    下级地区：
        <ul>
            {% for a in area.areainfo_set.all %}
            <li> {{a.atitle}} </li>
            {% empty %}
            <li>没有下级地区</li>
            {% endfor %}
        </ul>
</body>
</html>

demo1/templates/booktest/bookadd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加图书</title>
</head>
<body>
    <div class="div1">
        <h1>添加图书</h1>
        <form action="{% url 'booktest:addbook' %}" method="post">
            图书名：<input type="text" name="bookname">
            <input type="submit" value="提交">
        </form>
        <a href="{% url 'booktest:list' %}">返回列表页</a>
    </div>
</body>
</html>

demo1/templates/booktest/bookupdate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑图书</title>
</head>
<body>
    <div class="div1">
        <h1>编辑图书</h1>
        <form action="{% url 'booktest:updatebook' %}" method="post">
            图书名：<input type="text" placeholder="{{book.btitle}}" name="bookname">
            <input type="hidden" value="{{book.id}}" name="bookid">
            <input type="submit" value="提交">
        </form>
        <a href="{% url 'booktest:list' %}">返回列表页</a>
    </div>
</body>
</html>

demo1/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="div1">
        <h2>书名:{{Bookdata.btitle}}</h2>

        <ul>
            {% for hero in Bookdata.heroinfo_set.all %}
                <li>{{ hero.hname }}--------{{hero.hcontent}}
                    <a href="{% url 'booktest:herodelete' hero.id %}">删除</a>
                    <a href="{% url 'booktest:heroupdate' hero.id %}">编辑</a>
                </li>
            {% empty %}
                <h3>没有人物</h3>
            {% endfor%}
        </ul>

        {# <a href="/booktest/list/">返回列表页</a> #}
        <a href="{% url 'booktest:list' %}">返回列表页</a>
        <a href="{% url 'booktest:heroadd' Bookdata.id %}">添加人物</a>
    </div>
</body>
</html>

demo1/templates/booktest/heroadd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加人物</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
        <div class="div1">
            <form action="{% url 'booktest:heroinfoadd' %}" method="post">
                人物名： <input type="text" name="heroname">
                <br>
                性别：<input type="radio" value="1" name="sex" checked>男
                <input type="radio" value="0" name="sex">女
                <br>
                绝招：<input type="text" name="herocontent">
                <input type="hidden" value="{{bookid}}" name="bookid">
                <br>
                <input type="submit" value="提交">
            </form>
        </div>
</body>
</html>

demo1/templates/booktest/heroupdate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>人物修改</title>
</head>
<body>
    <div class="div1">
        <form action="{% url 'booktest:addheroinfo' %}" method="post">
            人物名：<input type="text" value="{{hero.hname}}" name="heroname">
            <br>
            {% if hero.hgender %}
            性别：<input type="radio" value="1" name="sex" checked>男
            <input type="radio" value="0" name="sex">女
            {% else %}
            性别：<input type="radio" value="1" name="sex" checked>男
            <input type="radio" value="0" name="sex" checked>女
            {% endif %}
            <br>
            绝招：<input type="text" value="{{hero.hcontent}}" name="herocontent">
            <br>
            <input type="hidden" value="{{hero.id}}" name="heroid">
            <input type="hidden" value="{{hero.hbook}}" name="hbook">
            <input type="submit" value="提交">
        </form>
        <a href="{% url 'booktest:list' %}">返回列表页</a>
    </div>
</body>
</html>

demo1/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    {% load static from staticfiles %}
    {# <link rel="stylesheet" href="/static/css/main.css"> #}
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
</head>
<body>
    <div class="div1">
        {# <img src="/static/img/314249.jpg" alt="" width="1100px"> #}
        <img src="{% static '/img/314249.jpg' %}" alt="加载失败" width="1100px">
        {% if username %}
            <h2>{{ username }}</h2>
            <a href="{% url 'booktest:logout' %}"> 退出登录</a>
        {% else %}
            <h2>没有登录</h2>
            <a href="{% url 'booktest:login' %}">点击登录</a>
        {% endif%}

        {# <a href="/booktest/list/">列表页</a> #}
            <a href=" {% url 'booktest:list' %} ">列表页</a>
    </div>
</body>
</html>

demo1/templates/booktest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="div1">
        <h1>书籍信息</h1>

        <ul>
            {% for book in booklist %}
                {#<li><a href="/booktest/details/{{book.id}}/"> {{ book.btitle }} </a> </li>#}
                <li><a href="{% url 'booktest:details' book.id %}"> {{ book.btitle }} </a> 
                    <a href="{% url 'booktest:delete' book.id %}">删除</a>
                    <a href="{% url 'booktest:bookupdate' book.id %}">编辑</a>
                </li>
            {% empty%}
                <h3>没有书籍</h3>
            {% endfor %}
        </ul>
            <a href="{% url 'booktest:index' %}">返回首页</a>
            <a href="{% url 'booktest:bookadd' %}">添加图书</a>
             <!--<a href="/booktest/addbook.html">添加</a>-->
    </div>
</body>
</html>

demo1/templates/booktest/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
        <div class="div1">
            <form action="#" method="post">
                用户名：<input type="text" name="username">
                <input type="submit" value="登录">
            </form>
        </div>
</body>
</html>